### ISSUE TITLE
values with whitespaces

### ISSUE THREAD

**Issue by minikN** [budlabs/mondo#10]
Hello.

Am I correct that it is not allowed to have values with whitespaces in my theme file?

For example:

`MONDO_DIR\themes\mytheme`:
`myvar    "hello world"`

if I do `mondo -l vars mytheme` it only parses the `"hello` part of the value. Can this be fixed?

**Comment by budRich** [comment]
hello @minikN !
Thanks for reporting this, it was a small bug in the list function that caused this, spaces in values was expanded when generating, so this bug was only visible when listing a theme like this. The fix will be added in the next version (i will probably release it today) of mondo!

Have a great day!
