### ISSUE TITLE
No mondo resources when running "mondo -l resources"

### ISSUE THREAD

**Issue by Flores02** [budlabs/mondo#3]
Hello BudRich,

I would like to thank you for all your work around i3-wm tiling and ricing, it really makes it seem easier to do and save from hours of research and testing.

I decided today to use your mondo tool to manage themes in my i3-wm.
I started following your videos tutorials and created a theme as you suggested without parsing any file to it just a simple command:

`mondo -n mytheme`

If this would have worked like you stated in your video I would have some mondo resources defined in it right? Like that:

#define fg #bdae93
#define bg #252323

#define base00 #252323
#define base01 #8f3f71
#define base02 #427b58
#define base03 #32302F

#define base0 #b57614
#define base1 #bdae93
#define base2 #ebdbb2
#define base3 #f9f5d7

#define red #cc241d
#define ora #9d0006
#define grn #98971a
#define ylw #d79921
#define blu #458588
#define mag #b16286
#define vio #076678
#define cyn #689d6a

mondo.colors.fg1:         fg
mondo.colors.fg2:         base2
mondo.colors.bg1:         bg
mondo.colors.bg2:         base03

mondo.colors.dark1:       base00
mondo.colors.light1:      base3

mondo.colors.act1:        blu
mondo.colors.act2:        base3
mondo.colors.act3:        base00

mondo.colors.ina1:        base03
mondo.colors.ina2:        fg
mondo.colors.ina3:        base2

mondo.colors.sel1:     base00
mondo.colors.sel2:     base3

!! GUI theme
#define cursortheme     Adwaita  
#define icontheme       ePapirus
#define gtktheme        buddybud 

!! Terminal fonts
#define terminalfontface1 monospace
#define terminalfontsize1 12
#define terminalfontface2 monospace
#define terminalfontsize2 18

!! GUI fonts
#define guifontface1      monospace
#define guifontsize1      12
#define guifontface2      sans
#define guifontsize2      18

Because it takes kind of inspiration from Xresources by default (also nitce my .Xresources file looks exactly like yours in your tutorials, importing colors and urxvt file).

So my theme file looks like this:

 !! Theme:    mytheme                                                                                
 !! Author:   dreamer
 !! Created:  2018-08-30
 
 bg           #222222
 bg2          #333333

 fg           #DDDDDD
 comment      #AAAAAA
  
 red          #FF0000
 green        #00FF00
 blue         #0000FF
 yellow       #FFFF00
 cyan         #00FFFF
 magenta      #FF00FF
  
 dark         #000000
 light        #FFFFFF
  
 activebg     cyan
 activefg     light
 activehl     dark
 
 inactivebg   blue
 inactivefg   fg

 selectedbg   magenta
 selectedfg   light

It produces something similar to this even if I parse an Xresources type file from the unixporn contest you linked up in your video. But by reading the README of the latest mondo version I found out that the synopsis for creating a new theme has changed like you can't parse a file anymore? Just a name?

I watched your videos multiple times to find where I could have done something wrong but I don't find my error maybe something changed in newer mondo versions? I also output my xrdb resources and everything is fine on this part. I'm really stuck and dont know how to solve this...

Thank you for reading,
Hope you can give me a hand,
Thanks :)

**Comment by budRich** [comment]
@Flores02 thanks for testing Mondo! I am really sorry, this is one problem with having the youtube. I have made a big update to mondo, and some things are different from how they appear in the videos.  

Most important, xrdb/xresoruces is no longer a dependcy. This means that the resources are no longer bound to to xresources strange naming convention and stuff.  So instead of listing resources, you can now do: mondo -l vars , that will list all variables. Another important difference is that the var names now doesn't need the mondo. prefix.

My best advice is to read the mondo documentation (mondo -h or the readme) and also have a look at my personal mondo config files (be aware that some fonts and icon themes might not match yours):  

https://github.com/budlabs/mondo-contrib

the "lets" directory is my ~/.config/mondo directory.

Another approach you can take is.
Use the old version of mondo that i use in the videos:
https://github.com/budlabs/mondo/releases/tag/v.0.0.1

But this new version is much smarter and better.

I think i should make new mondo videos, updated to the new version and remove the old ones to not create too much confusion. I will start making these videos tonight.

**Comment by Flores02** [comment]
Thank you really much will do what you said and keep you up to date! Keep it up i love mondo it makes life so much easier!

**Comment by budRich** [comment]
https://youtu.be/flyFguRc53M
